import React, { memo } from 'react';
import type { Metadata } from 'next';
import NavBar from './_components/navbar';
import Footer from './_components/footer';

// These styles apply to every route in the application
import '../styles/main.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={'bg-neutral7'}>
        <div className="relative isolate overflow-hidden aiu min-h-screen bg-neutral7 scrollbar-hide">
          <BackgroundPattern />
          <NavBar />
          <main className={'w-full h-full flex items-center justify-center'}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}

const BackgroundPattern = memo(() => (
  <svg
    className="absolute inset-0 -z-10 h-full w-full bew"
    aria-hidden="true"
    style={{
      stroke: 'rgb(255 255 255 / 0.1)'
    }}
  >
    <defs>
      <pattern
        id="983e3e4c-de6d-4c3f-8d64-b9761d1534cc"
        width="200"
        height="200"
        x="50%"
        y="-1"
        patternUnits="userSpaceOnUse"
      >
        <path d="M.5 200V.5H200" fill="none"></path>
      </pattern>
    </defs>
    <svg
      x="50%"
      y="-1"
      className="overflow-visible aol"
      style={{
        fill: 'rgb(31 41 55 / 0.2)'
      }}
    >
      <path
        d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z"
        strokeWidth="0"
      ></path>
    </svg>
    <rect
      width="100%"
      height="100%"
      strokeWidth="0"
      fill="url(#983e3e4c-de6d-4c3f-8d64-b9761d1534cc)"
    ></rect>
  </svg>
));
